services:
  db:
    image: mariadb:10.6.8
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --log-bin=mysqld-bin
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD
    networks:
      - default

  redis:
    image: redis:7.0.2
    command: redis-server --requirepass "${REDIS_HOST_PASSWORD}"
    restart: always
    networks:
      - default

  app:
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - ${NEXTCLOUD_DATA_PATH}:/var/www/html/data
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD
      - SMTP_HOST
      - SMTP_SECURE
      - SMTP_PORT
      - SMTP_NAME
      - SMTP_PASSWORD
      - MAIL_FROM_ADDRESS
      - MAIL_DOMAIN
      - PHP_UPLOAD_LIMIT=10G
      - OVERWRITEPROTOCOL=https
      - NC_default_phone_region=US
      - VIRTUAL_HOST
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      - default
      - proxy
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
  apps:
  config:

networks:
  proxy:
    name: nginx-proxy
    external: true
